services:
  nginx:
    image: nginx:1.21.1
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/
    depends_on:
      - php
    networks:
      - default
    platform: linux/arm64 

  php:
    build: ./docker/php
    volumes:
      - ./src:/var/www/
    networks:
      - default
    platform: linux/arm64 

  mysql:
    image: arm64v8/mysql:8.0 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    command:
      mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - default
    platform: linux/arm64 

  phpmyadmin:
    image: arm64v8/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=laravel_user
      - PMA_PASSWORD=laravel_pass
    depends_on:
      - mysql
    ports:
      - 8080:80
    networks:
      - default
    platform: linux/arm64 

  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
        - '1025:1025'
        - '8025:8025'
    networks:
        - default
    platform: linux/arm64 

networks:
  default:
    driver: bridge
